force-app/main/default/objects/Clinic__c/Clinic__c.object-meta.xml
<CustomObject>
    <label>Clinic</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Specialization__c/fields/Appointment_Price__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Price__c</fullName>
    <label>Appointment Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Specialization__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Specializations</relationshipLabel>
    <relationshipName>Specializations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialization__c/fields/Diagnosis_Duration_In_minutes__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Duration_In_minutes__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Diagnosis Duration (In minutes)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SpecializationController.cls
public with sharing class SpecializationController {
    @AuraEnabled
    public static List<Specialization__c> getSpecializations() {
        return [SELECT Id, Name, Appointment_Price__c, Clinic__c, Diagnosis_Duration_In_minutes__c FROM Specialization__c];
    }

    @AuraEnabled
    public static List<Specialization__c> getSpecializationsByClinic(String clinicId) {
        clinicId = String.escapeSingleQuotes(clinicId);
        return [SELECT Id, Name, Appointment_Price__c, Clinic__c, Diagnosis_Duration_In_minutes__c FROM Specialization__c];
    }
}