force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>Apt-{0000}</displayFormat>
        <label>Appointment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Specialization</label>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Specialization__c/Specialization__c.object-meta.xml
<CustomObject>
    <label>Specialization</label>
    <nameField>
        <label>Specialization</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Specializations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DashboardController.cls
public with sharing class DashboardController {
    @AuraEnabled
    public static List<GraphData> getAppointmentByPhysician() {
        List<GraphData> graphData = new List<GraphData>();
        for (AggregateResult result : [
            SELECT Physician__c, Physician__r.Name name, Count(id) total
            FROM Appointment__c
            GROUP BY Physician__c, Physician__r.Name
        ]) {
            GraphData data = new GraphData();
            data.id = String.valueOf(result.get('Physician__c'));
            data.name = String.valueOf(result.get('name'));
            data.count = Integer.valueOf(result.get('total'));
            graphData.add(data);
        }
        return graphData;
    }

    @AuraEnabled
    public static List<GraphData> getAppointmentBySpecialization() {
        List<GraphData> graphData = new List<GraphData>();
        for (AggregateResult result : [
            SELECT Physician__r.Specialization__c specialization, Physician__r.Specialization__r.Name specializationName, Count(id) total
            FROM Appointment__c
            GROUP BY Physician__r.Specialization__c, Physician__r.Specialization__r.Name
        ]) {
            GraphData data = new GraphData();
            data.id = String.valueOf(result.get('specialization'));
            data.name = String.valueOf(result.get('specializationName'));
            data.count = Integer.valueOf(result.get('total'));
            graphData.add(data);
        }
        return graphData;
    }

    public class GraphData {
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String name;
        @AuraEnabled
        public Integer count;
    }
}